### ISSUE TITLE
ToDoList

### ISSUE THREAD

**Issue by PineApple777** [SoftwareEngineeringG4/CSE4006#8]
- 현재 폴더 구조
project-folder/
   &nbsp;&nbsp;&nbsp;&nbsp;| server/
   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;| controller/
   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;| db/
   &nbsp;&nbsp;&nbsp;&nbsp;| src/
   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;| css/
   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;| fonts/
   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;| img/
   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;| js/
0. server/ : 서버 시작 파일들과 관련 폴더들
1. server/controller/ : 서버에서 작업할 클래스들이 들어가야하는 부분
2. server/db/ : db 관련 파일들이 존재.
3. src/ : html 파일들 및 필요한 폴더들 있음
4. src/css/ : css 파일들이 있음
5. src/img/ : 사진들을 모아두는 곳
6. src/js/ : javascript 파일들을 모아두는 곳
7. src/fonts/ : 폰트 관련 파일들
![class](https://user-images.githubusercontent.com/14249278/49456559-ad078200-f82c-11e8-976e-6ab10765f17f.png)
- 현재 구현할 클래스
1. userinfo ( UserInfoManager ) - 80% 완성
2. board ( BoardManager )
3. Admin ( AdminManager )
4. search

* Userinfo를 제외한 다른 클래스들은 네이밍은 위 둘 중 하나로 정하기 괄호 없 vs 괄호 있
** 헤당 ToDo 내용이 끝나면 댓글로 추가

@PineApple777 
 - 관리자 페이지의 등록 버튼 기능 구현 
 -  board 및 search 클래스 구현하기
 - Server 와 Client 데이터 전달 되도록 연결
 - 추후에 Layer.html 파일 추가 및 각 파일별 코드 리펙토링

@jinmyeonglee 
- 테스트 데이터 엑셀로 정리
- Admin class 구현하기 => controller/ 폴더에 파일 생성 후, 필요한 instance 및 메소드 추가
- 해당 Admin에서 주고 받는 데이터 이슈에 정리 ( EX> boardCreate() ==> return boardname, htmlname etc. )

@andr812
- 내 글 확인 페이지 ( myPost.html ) 추가
- admin.html 에 각 기능별 form 및 submit 속성 추가
- search 게시판 예시페이지 ( search.html ) static하게 예시 추가

>> 궁금한점 댓글로 무조건! @PineApple777 요런식으로 태그 달기!

**Comment by PineApple777** [comment]
[@ pull request #9](https://github.com/SoftwareEngineeringG4/CSE4006/pull/9#issue-235887312)

**Comment by PineApple777** [comment]
@jinmyeonglee 
혹시 디비 Post 테이블에서 bid 왜래키 board 테이블 참조하도록 설정 하셨나요
가능하다면 부탁드립니당

**Comment by andr812** [comment]
@PineApple777 Todo 모두 완료! 내 글 확인 페이지->(index.html) 이므로 게시판 페이지( noticeboard.html ) 추가하였습니다!

**Comment by jinmyeonglee** [comment]
@PineApple777 넹 foreign key 원래 참조하도록 했었습니다. show create table 쿼리로 확인해보세용!

**Comment by jinmyeonglee** [comment]
@PineApple777 Admin 만들긴했는데 이거 돌려보고 디버깅해야될텐더 어떤식으로 하면 되나요?ㅡㅜ

**Comment by PineApple777** [comment]
@jinmyeonglee 일단 개인 레포에 커밋해주세용^^7 풀리퀘 하게 되시면 설명 적어주세용~

**Comment by PineApple777** [comment]
[add classes #12](https://github.com/SoftwareEngineeringG4/CSE4006/pull/12)
[Add Admin class #11](https://github.com/SoftwareEngineeringG4/CSE4006/pull/11)
[request done #10](https://github.com/SoftwareEngineeringG4/CSE4006/pull/10)
